config/routes.rb
Rails.application.routes.draw do
  resources :providers
  resources :messages
  resources :forecasts
  resources :notifications
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'privacy' => 'welcome#privacy'

  # twilio webhook
  post 'twilio/sms' => 'twilio#sms'
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: %i[ show edit update destroy ]

  # GET /providers or /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1 or /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers or /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: "Provider was successfully created." }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1 or /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: "Provider was successfully updated." }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1 or /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: "Provider was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def provider_params
      params.require(:provider).permit(:name, :endpoint, :elevation, :disabled)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_with(model: provider) do |form| %>
  <% if provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
        <% provider.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, disabled: true%>
  </div>

  <div class="field">
    <%= form.label :endpoint %>
    <%= form.text_field :endpoint, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :elevation %>
    <%= form.select :elevation, options_for_select(['5500', '6500', '7500', '8035'], selected: form.object.elevation ) %>
  </div>

  <div class="field">
    <%= form.label :disabled %>
    <%= form.check_box :disabled, disabled: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Endpoint</th>
      <th>Elevation</th>
      <th>Disabled</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.endpoint %></td>
        <td><%= provider.elevation %></td>
        <td><%= provider.disabled %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %>

app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form', provider: @provider %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Endpoint:</strong>
  <%= @provider.endpoint %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @provider.elevation %>
</p>

<p>
  <strong>Disabled:</strong>
  <%= @provider.disabled %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>